only_rules:
  - trailing_whitespace
  - trailing_newline
  - line_length
  - file_length
  - type_body_length

line_length: 140
file_length:
  warning: 500
  error: 600
type_body_length:
  warning: 300
  error: 400

excluded:
  - .build
  - .swiftpm
  - Packages
  - .git
